### PR TITLE
Update plugin to support Graylog V2.0+. Also update settings screen t…

### PR DESCRIPTION
**Pull request by twcollins**
…o utilise non text field widgets where appropriate to assist ease of configuration.

### CODE REVIEW

**Comment by huksley** [comment]
Thanks for your contribution! Accepted all and will remove all Eclipse configuration now.

**Comment by huksley** [comment]
Please explain the reason to create uber-jar using shade plugin. I suppose all the dependencies from Graylog server is available to plugins in classpath? It is potentially dangerous to duplicate dependencies as it can lead to hard to debug classpath problems.

**Comment by tcollins-rms** [comment]
The main reason for creating the uber-jar was to make deployment a little easier.   I went with shade for the uber-jar because it seems to be the convention that has emerged across the graylog plugins in graylog core itself. 
Agreed re the potential increase in debug effort if a classpath clash were to emerge. Maybe update the dependency scope to `provided`?  I'm happy to submit a fresh PR for this if you think that'll address concerns.

**Comment by huksley** [comment]
All the dependencies used by plugin are provided by Graylog server. I believe they don`t need to be packaged with plugin. Can you provide another pull request? I will happily merge it right away.

**Pull request merged**
